channels:
- conda-forge
dependencies:
- python=3.9.5
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - databricks-automl-runtime==0.2.11
  - holidays==0.15
  - mypy-extensions==0.4.3
  - pandas==1.3.4
  - psutil==5.8.0
  - scikit-learn==0.24.2
  - typing-extensions==3.10.0.2
  - xgboost==1.6.2
name: mlflow-env
